"""
==================================================
Author: Jan Nalepka
Script version: 2.0
Date: 2024-12-02
Repository: https://github.com/jnalepka/grenton-to-homeassistant
==================================================
"""

DOMAIN = 'grenton_objects'
CONF_API_ENDPOINT = 'api_endpoint'
CONF_GRENTON_ID = 'grenton_id'
CONF_GRENTON_TYPE = 'grenton_type'
CONF_GRENTON_TYPE_UNKNOWN = 'UNKNOWN'
CONF_GRENTON_TYPE_DOUT = 'DOUT'
CONF_GRENTON_TYPE_DIMMER = 'DIMMER'
CONF_GRENTON_TYPE_RGB = 'RGB'
CONF_GRENTON_TYPE_LED_R = 'LED_R'
CONF_GRENTON_TYPE_LED_G = 'LED_G'
CONF_GRENTON_TYPE_LED_B = 'LED_B'
CONF_GRENTON_TYPE_LED_W = 'LED_W'
CONF_GRENTON_TYPE_DEFAULT_SENSOR = 'DEFAULT_SENSOR'
CONF_GRENTON_TYPE_MODBUS_RTU = 'MODBUS_RTU'
CONF_GRENTON_TYPE_MODBUS_VALUE = 'MODBUS_VALUE'
CONF_GRENTON_TYPE_MODBUS = 'MODBUS'
CONF_GRENTON_TYPE_MODBUS_CLIENT = 'MODBUS_CLIENT'
CONF_GRENTON_TYPE_MODBUS_SERVER = 'MODBUS_SERVER'
CONF_GRENTON_TYPE_MODBUS_SLAVE_RTU = 'MODBUS_SLAVE_RTU'
CONF_OBJECT_NAME = 'name'
CONF_REVERSED = 'reversed'
CONF_DEVICE_CLASS = 'device_class'
CONF_STATE_CLASS = 'state_class'
CONF_UNIT_OF_MEASUREMENT = 'unit_of_measurement'
CONF_DEVICE_TYPE = 'device_type'
CONF_DEVICE_TYPE_LIGHT = 'light'
CONF_DEVICE_TYPE_SWITCH = 'switch'
CONF_DEVICE_TYPE_COVER = 'cover'
CONF_DEVICE_TYPE_CLIMATE = 'climate'
CONF_DEVICE_TYPE_SENSOR = 'sensor',
CONF_DEVICE_TYPE_BINARY_SENSOR = 'binary_sensor'
CONF_DEVICE_TYPE_BUTTON = 'button'
