set_state:
  name: Ustaw stan encji Grenton
  description: Ręcznie ustawia stan encji Grenton jako 1 (ON) lub 0 (OFF).
  fields:
    entity_id:
      name: Encja
      description: Encja, której stan ma zostać zmieniony.
      required: true
      selector:
        entity:
          domain:
            - binary_sensor
            - switch
            - light
    state:
      name: Stan docelowy
      description: Wartość stanu (1 = ON, 0 = OFF).
      required: true
      selector:
        number:
          min: 0
          max: 1
          step: 1
          mode: box

set_brightness:
  name: Ustaw stan/jasność encji Grenton
  description: Ręcznie ustawia stan/jasność encji Grenton w zakresie 0.00 (0%, OFF) do 1.00 lub 255 (100%).
  fields:
    entity_id:
      name: Encja
      description: Encja, której stan ma zostać zmieniony.
      required: true
      selector:
        entity:
          domain:
            - light
    brightness:
      name: Jasność
      description: Wartość jasności od 0.00 do 1.00 lub 255.
      required: true
      selector:
        number:
          min: 0
          max: 255
          step: 0.01
          mode: box

set_rgb:
  name: Ustaw kolor encji Grenton
  description: Ręcznie ustawia kolor encji Grenton wg modelu RGB #RRGGBB (podawana w HEX).
  fields:
    entity_id:
      name: Encja
      description: Encja, której stan ma zostać zmieniony.
      required: true
      selector:
        entity:
          domain:
            - light
    hex:
      name: Kolor (hex)
      description: Wartość koloru wg modelu RGB #RRGGBB (podawana w HEX).
      required: true
      selector:
        text:
          multiline: false
